Telefon Rehberi/Areas/Admin/Controllers/GirisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using Rehber.Bl.Interface;
using Telefon_Rehberi.Areas.Admin.Models.Giris;
using Telefon_Rehberi.Helpers;

namespace Telefon_Rehberi.Areas.Admin.Controllers
{
    public class GirisController : Controller
    {
        private IAyarlarYonetimi _ayarlarYonetimi;

        public GirisController(IAyarlarYonetimi ayarlarYonetimi)
        {
            _ayarlarYonetimi = ayarlarYonetimi;
        }

        // GET: Admin/Giris
        public ActionResult Index(string pass)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "UI");
            }
            else
            {
                if (!String.IsNullOrEmpty(pass))
                {
                    GirisViewModel model = new GirisViewModel()
                    {
                        Pass = pass
                    };
                    return View(model);
                }
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(GirisViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Pass == _ayarlarYonetimi.Get(a => a.Anahtar == "AdminPass").Deger)
                {
                    Session["UserName"] = "Admin";
                    return RedirectToAction("Index", "UI");
                }
            }

            this.ErrorMessage("Şifre yanlış!");
            return RedirectToAction("Index");
        }

        public ActionResult Cikis()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();

            return RedirectToAction("Index", "Home", new { Area = "" });
        }

        [UserAuthorize]
        public ActionResult Reset()
        {
            GirisResetViewModel model = new GirisResetViewModel();

            return View(model);
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult Reset(GirisResetViewModel model)
        {
            try
            {
                if (model.newPass == model.newPass2)
                {
                    var Pass = _ayarlarYonetimi.Get(a => a.Anahtar == "AdminPass");
                    if (model.oldPass == Pass.Deger)
                    {
                        if (model.oldPass != model.newPass)
                        {
                            Pass.Deger = model.newPass;
                            _ayarlarYonetimi.Update(Pass);

                            this.SuccessMessage("Admin şifresi başarıyla değiştirildi.");
                            return RedirectToAction("Index", "UI");
                        }
                        else
                        {
                            this.WarningMessage("Yeni şifre eski şifreden farklı olmalıdır!");
                        }
                    }
                    else
                    {
                        this.WarningMessage("Eski şifrenizi yanlış girdiniz!");
                    }
                }
                else
                {
                    this.WarningMessage("Yeni şifreniz eşleşmiyor!");
                }
            }
            catch (Exception e)
            {
                this.ErrorMessage($"Bir hata oluştu! ({e.Message})");
            }

            return View(model);
        }
    }
}

Telefon Rehberi/Areas/Admin/Controllers/UIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rehber.Bl.Interface;
using Telefon_Rehberi.Areas.Admin.Models.UI;
using Telefon_Rehberi.Helpers;

namespace Telefon_Rehberi.Areas.Admin.Controllers
{
    [UserAuthorize]
    public class UIController : Controller
    {
        private ICalisanYonetimi _calisanYonetimi;
        private IDepartmanYonetimi _departmanYonetimi;

        public UIController(ICalisanYonetimi calisanYonetimi, IDepartmanYonetimi departmanYonetimi)
        {
            _calisanYonetimi = calisanYonetimi;
            _departmanYonetimi = departmanYonetimi;
        }

        public ActionResult Index()
        {
            UIViewModel model = new UIViewModel();
            model.CalisanList = _calisanYonetimi.GetAll().OrderBy(c => c.Ad).ThenBy(c => c.Soyad).ToList();
            model.DepartmanList = _departmanYonetimi.GetAll().OrderByDescending(d => d.tblCalisan.Count).ThenBy(d => d.Ad).ToList();

            return View(model);
        }
    }
}

Telefon Rehberi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Telefon Rehberi">
    <meta name="author" content="bgoktugozdemir">
    <title>@ViewBag.Title - Telefon Rehberi</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container w80">
            <a class="navbar-brand" href="@Url.Action("Index","Home", new { Area = ""})">Telefon Rehberi</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Home", new { Area = ""})">Ana Sayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","UI", new { Area = "Admin"})">Admin</a>
                    </li>
                    @if (Session["UserName"] != null)
                    {
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Cikis","Giris", new { Area = "Admin"})">Çıkış</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Reset","Giris", new { Area = "Admin"})">Şifreyi Sıfırla</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container w80">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="mt-5">Telefon Rehberi</h1>
                <p class="lead">Telefon rehberiniz hazır!</p>
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Site.js"></script>
</body>
</html>