Telefon Rehberi/Areas/Admin/Models/UI/UIViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Rehber.Model.DataModel;

namespace Telefon_Rehberi.Areas.Admin.Models.UI
{
    public class UIViewModel
    {
        public List<tblCalisan> CalisanList { get; set; }
        public List<tblDepartman> DepartmanList { get; set; }
    }
}

Telefon Rehberi/Areas/Admin/Controllers/CalisanYonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rehber.Bl.Interface;
using Rehber.Model.DataModel;
using Telefon_Rehberi.Areas.Admin.Models.CalisanYonetim;
using Telefon_Rehberi.Helpers;

namespace Telefon_Rehberi.Areas.Admin.Controllers
{
    [UserAuthorize]
    public class CalisanYonetimController : Controller
    {
        private ICalisanYonetimi _calisanYonetimi;
        private IDepartmanYonetimi _departmanYonetimi;

        public CalisanYonetimController(ICalisanYonetimi calisanYonetimi, IDepartmanYonetimi departmanYonetimi)
        {
            _calisanYonetimi = calisanYonetimi;
            _departmanYonetimi = departmanYonetimi;
        }

        // GET: Admin/CalisanYonetim
        public ActionResult CalisanDuzenle(int? id)
        {
            CalisanDuzenleViewModel model = new CalisanDuzenleViewModel();

            if (id != null)
            {
                model.Calisan = _calisanYonetimi.Get(c => c.ID == id);
                model.CalisanList = _calisanYonetimi.GetAll(c => c.ID != id).ToList();
            }
            else
            {
                model.CalisanList = _calisanYonetimi.GetAll().ToList();
            }

            var calisanlar = model.CalisanList.Select(c => new
            {
                Text = c.Ad + " " + c.Soyad,
                Value = c.ID
            }).ToList();
            model.CalisanSelectList = new SelectList(calisanlar, "Value", "Text");

            model.DepartmanList = _departmanYonetimi.GetAll().OrderBy(d => d.Ad).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult CalisanDuzenle(CalisanDuzenleViewModel model)
        {
            try
            {
                _calisanYonetimi.AddOrUpdate(model.Calisan);

                this.SuccessMessage($"<strong>{model.Calisan.Ad + " " + model.Calisan.Soyad}</strong> isimli çalışan başarıyla kaydedildi!");
            }
            catch (Exception e)
            {
                this.ErrorMessage($"Çalışan kaydedilirken bir hata ile karşılaşıldı! <strong>({e.Message})</strong>");
            }

            return RedirectToAction("Index", "UI");
        }

        public ActionResult CalisanSil(int id)
        {
            var calisanSayisi = _calisanYonetimi.Get(d => d.ID == id).tblCalisan1.Count;
            if (calisanSayisi > 0)
            {
                this.ErrorMessage($"Bu çalışanın altında <strong>{calisanSayisi}</strong> çalışan bulunmaktadır.");
            }
            else
            {
                _calisanYonetimi.Delete(id);

                this.WarningMessage("Çalışan Silindi!");
            }

            return RedirectToAction("Index","UI");
        }

        public string CalisanAdGetir(int id)
        {
            var calisan = _calisanYonetimi.Get(c => c.ID == id);

            return (calisan.Ad + " " + calisan.Soyad).ToUpper();
        }
    }
}

Telefon Rehberi/Areas/Admin/Controllers/DepartmanYonetimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rehber.Bl.Interface;
using Telefon_Rehberi.Areas.Admin.Models.DepartmanYonetim;
using Telefon_Rehberi.Helpers;

namespace Telefon_Rehberi.Areas.Admin.Controllers
{
    [UserAuthorize]
    public class DepartmanYonetimController : Controller
    {
        private IDepartmanYonetimi _departmanYonetimi;

        public DepartmanYonetimController(IDepartmanYonetimi departmanYonetimi)
        {
            _departmanYonetimi = departmanYonetimi;
        }

        // GET: Admin/DepartmanYonetim
        public ActionResult DepartmanDuzenle(int? id)
        {
            DepartmanDuzenleViewModel model = new DepartmanDuzenleViewModel();

            if (id != null)
            {
                model.Departman = _departmanYonetimi.Get(d => d.ID == id);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult DepartmanDuzenle(DepartmanDuzenleViewModel model)
        {
            try
            {
                _departmanYonetimi.AddOrUpdate(model.Departman);

                this.SuccessMessage($"<strong>{model.Departman.Ad}</strong> departmanı başarıyla kaydedildi.");
            }
            catch (Exception e)
            {
                this.ErrorMessage($"Departman kaydedilirken bir hata ile karşılaşıldı! <strong>({e.Message})</strong>");
            }



            return RedirectToAction("Index", "UI");
        }

        public ActionResult DepartmanSil(int id)
        {
            var calisanSayisi = _departmanYonetimi.Get(d => d.ID == id).tblCalisan.Count;
            if (calisanSayisi > 0)
            {
                this.ErrorMessage($"Bu departmana kayıtlı <strong>{calisanSayisi}</strong> çalışan bulunmaktadır.");
            }
            else
            {
                _departmanYonetimi.Delete(id);

                this.WarningMessage("Departman Silindi!");
            }

            return RedirectToAction("Index", "UI");
        }
    }
}

Telefon Rehberi/Areas/Admin/Controllers/UIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rehber.Bl.Interface;
using Telefon_Rehberi.Areas.Admin.Models.UI;
using Telefon_Rehberi.Helpers;

namespace Telefon_Rehberi.Areas.Admin.Controllers
{
    [UserAuthorize]
    public class UIController : Controller
    {
        private ICalisanYonetimi _calisanYonetimi;
        private IDepartmanYonetimi _departmanYonetimi;

        public UIController(ICalisanYonetimi calisanYonetimi, IDepartmanYonetimi departmanYonetimi)
        {
            _calisanYonetimi = calisanYonetimi;
            _departmanYonetimi = departmanYonetimi;
        }

        public ActionResult Index()
        {
            UIViewModel model = new UIViewModel();
            model.CalisanList = _calisanYonetimi.GetAll().OrderBy(c => c.Ad).ThenBy(c => c.Soyad).ToList();
            model.DepartmanList = _departmanYonetimi.GetAll().OrderByDescending(d => d.tblCalisan.Count).ThenBy(d => d.Ad).ToList();

            return View(model);
        }
    }
}

Telefon Rehberi/Areas/Admin/Views/UI/Index.cshtml
@model Telefon_Rehberi.Areas.Admin.Models.UI.UIViewModel
@{
    ViewBag.Title = "Admin UI";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    @if (TempData["Alert"] != null)
    {
        @Html.Raw(TempData["Alert"].ToString())
    }
    <div class="col-md-9">
        <div>
            <a href="@Url.Action("CalisanDuzenle", "CalisanYonetim")" class="btn btn-success float-right">
                <i class="fa fa-plus"></i> Yeni Çalışan Ekle
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">AD</th>
                    <th scope="col">SOYAD</th>
                    <th scope="col">TELEFON</th>
                    <th scope="col">DEPARTMAN</th>
                    <th scope="col">YÖNETİCİ</th>
                    <th scope="col">İŞLEMLER</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var calisan in Model.CalisanList)
                {
                    <tr>
                        <th scope="row">@calisan.ID</th>
                        <td>@calisan.Ad.ToUpper()</td>
                        <td>@calisan.Soyad.ToUpper()</td>
                        <td>@calisan.Telefon</td>
                        <td>@((calisan.DepartmanID == null) ? "-" : @calisan.tblDepartman.Ad.ToUpper())</td>
                        <td>@((calisan.tblCalisan2 == null) ? "-" : (calisan.tblCalisan2.Ad + " " + calisan.tblCalisan2.Soyad).ToUpper())</td>
                        <td>
                            <a href="@Url.Action("CalisanDuzenle", "CalisanYonetim", new {id = calisan.ID})" class="text-warning">
                                <i class="fa fa-edit"></i>
                            </a>

                            <a href="@Url.Action("CalisanSil", "CalisanYonetim", new {id = calisan.ID})" class="text-danger">
                                <i class="fa fa-remove"></i>
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-3">
        <div>
            <a href="@Url.Action("DepartmanDuzenle", "DepartmanYonetim")" class="btn btn-dark float-right float-sm-left">
                <i class="fa fa-plus"></i> Yeni Departman Ekle
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col">Ad</th>
                        <th scope="col">Çalışan Sayısı</th>
                        <th scope="col">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var departman in Model.DepartmanList)
                    {
                        <tr>
                            <td>@departman.Ad</td>
                            <td>@departman.tblCalisan.Count</td>

                            <td>
                                <a href="@Url.Action("DepartmanDuzenle", "DepartmanYonetim", new {id = departman.ID})" class="text-warning">
                                    <i class="fa fa-edit"></i>
                                </a>

                                <a href="@Url.Action("DepartmanSil", "DepartmanYonetim", new {id = departman.ID})" class="text-danger">
                                    <i class="fa fa-remove"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>